apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: name-service-nodejs-circuit-breaker
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/lholmqui-tenant/nodejs-circuit-breaker/name-service-nodejs-circuit-breaker@sha256:e9c42dd57634c761ea67ed88872fa036c35def7d8309e79423c2bb50f1c58453
        name: my-nodejs
        resources: {}
status: {}
