apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: name-service-nodejs-circuit-breaker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: name-service-nodejs-circuit-breaker
    app.kubernetes.io/part-of: nodejs-circuit-breaker
  name: name-service-nodejs-circuit-breaker
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: name-service-nodejs-circuit-breaker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: name-service-nodejs-circuit-breaker
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/lholmqui-tenant/nodejs-circuit-breaker/name-service-nodejs-circuit-breaker@sha256:e9c42dd57634c761ea67ed88872fa036c35def7d8309e79423c2bb50f1c58453
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
