apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: greeting-service-nodejs-circuit-breaker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: greeting-service-nodejs-circuit-breaker
    app.kubernetes.io/part-of: nodejs-circuit-breaker
  name: greeting-service-nodejs-circuit-breaker
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: greeting-service-nodejs-circuit-breaker
status:
  loadBalancer: {}
